export {default as Menu} from './Menu'
export {default as Connexion} from './Connexion'
export {default as Taches} from './AllTaches'
export {default as CreerTaches} from './CreerTaches'
export {default as DetailsTaches} from './DetailsTaches'
export {default as Parametres} from './Reglages'
